services:
  - type: web
    name: multicoin-heartbeat-bot
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: bot-logs
      mountPath: /app/logs
      sizeGB: 1
