__pycache__/
*.pyc
.venv/
.env
logs/
*.log
service
# =====================================================================
# Add render.yaml + .dockerignore into the Render-ready bot project
# =====================================================================
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# 0) Project path (adjust if your folder is elsewhere)
$ProjectRoot = Join-Path $env:USERPROFILE "Documents\multicoin_heartbeat_render_local_logs"

if (-not (Test-Path $ProjectRoot)) {
    Write-Host " Bot project folder not found at: $ProjectRoot" -ForegroundColor Red
    Write-Host "Edit `$ProjectRoot at the top of this script to your folder path." -ForegroundColor Yellow
    exit
}

Set-Location $ProjectRoot
Write-Host " Using project root: $ProjectRoot" -ForegroundColor Cyan

# 1) Create render.yaml
@'
# render.yaml  Infrastructure-as-code for Render

services:
  - type: web
    name: multicoin-heartbeat-bot
    env: docker
    plan: starter            # or 'free' / 'standard'
    autoDeploy: true
    healthCheckPath: /health
    # Render injects PORT; app_server.py reads PORT from env
    disk:
      name: bot-logs
      mountPath: /app/logs   # where trades.csv & heartbeat.log persist
      sizeGB: 1
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: SYMBOLS
        value: BTC-USD,ETH-USD,SOL-USD,LTC-USD,DOGE-USD,ADA-USD
      - key: TA_TIMEFRAME
        value: 1m
      - key: FAST_MA
        value: "3"
      - key: SLOW_MA
        value: "5"
      - key: TOTAL_EQUITY
        value: "10000"
